name: MACOSX CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
        fail-fast: false
        matrix:
          os: [macos-latest, windows-latest]
          cc: [clang]
          include:
          - os: macos-latest
            cc: clang
          exclude:
          - os: macos-latest
            cc: gcc
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: |
          release
