name: WINDOWS CI

on:
  push:
    branches: [ main ]
jobs:
  amd64_windows_clang:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - run: git submodule update --init --recursive
    - name: Web source build
      run: npm install
    - uses: msys2/setup-msys2@v2
      with:
        install: make mingw-w64-x86_64-clang git
    - run: clang --version
    - run: make CC=clang
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: reversing-emulator-canary-windows
        path: |
          release