name: WINDOWS CI

on:
  push:
    branches: [ main ]
jobs:
  amd64_windows_clang:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        install: make mingw-w64-x86_64-clang git
    - run: clang --version
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: make all
    - name: Web source NPM install
      run: cd libRetroReversing/websrc && C:\\hostedtoolcache\\windows\\node\\12.20.0\\x64\\npm install
    - name: Update path
      run: echo "C:\\hostedtoolcache\\windows\\node\\12.20.0\\x64\\" >> $GITHUB_PATH
    # - name: Web source build
      # run: cd libRetroReversing/websrc && C:\\hostedtoolcache\\windows\\node\\12.20.0\\x64\\npm run production --scripts-prepend-node-path C:\\hostedtoolcache\\windows\\node\\12.20.0\\x64
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: reversing-emulator-canary-windows
        path: |
          release